version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table which contains Airbnb listings
    columns:

      - name: listing_id
        description: Primary key for the listing
        data_tests:
          - unique
          - not_null
      - name: host_id
        description: Foreign Key. References the host table.
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id
      - name: room_type
        description: Type of the apartment/ room
        data_tests:
          - accepted_values:
              values: ['Entire home/apt',
                       'Private room',
                       'Shared room',
                       'Hotel room']
      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed_minimum_nights") }}'
        data_tests:
          - positive_value
  - name: dim_hosts_cleansed
    description: Cleansed table which contains Airbnb hosts
    columns:
      - name: host_id
        description: Primary Key for the host table
        data_tests:
          - not_null
          - unique
      - name: host_name
        description: Name of the host
        data_tests:
          - not_null
  - name: dim_listings_with_hosts
    description: N/A
    data_tests:
    - dbt_expectations.expect_table_row_count_to_equal_other_table:
        compare_model: source('airbnb', 'listings')
    columns:
      - name: price
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 50
              max_value: 500
          - dbt_expectations.expect_column_max_to_be_between:
              max_value: 5000
              config:
                severity: warn

